### PR TITLE
Add checks/badge for 1.59.0

### LINKED ISSUE #10: MSRV?
What's the minimum stable Rust version supported by this library? I've dug through the docs a bit and hadn't spotted any mention of a version.

### PR DESCRIPTION
**Pull request by palfrey**
Fixes #10

### CODE REVIEW

**Comment by thomcc** [comment]
I think this will hit the double panic in the condvar test I mentioned earlier. It would be nice to fix that.

Also, not every project needs to support an MSRV, so it's up to @kprotty if he cares to.

**Comment by kprotty** [comment]
Addressed the condvar double panic in #12

**Comment by kprotty** [comment]
Could you rebase on master?

**Comment by palfrey** [comment]
> Could you rebase on master?

Done

**Pull request merged**
